///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VSTSWebTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VSTSWebTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("1647540c-5d85-425e-95aa-9f98db6c861e")]
    public partial class VSTSWebTestRepository : RepoGenBaseFolder
    {
        static VSTSWebTestRepository instance = new VSTSWebTestRepository();
        VSTSWebTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the VSTSWebTestRepository element repository.
        /// </summary>
        [RepositoryFolder("1647540c-5d85-425e-95aa-9f98db6c861e")]
        public static VSTSWebTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VSTSWebTestRepository() 
            : base("VSTSWebTestRepository", "/", null, 0, false, "1647540c-5d85-425e-95aa-9f98db6c861e", ".\\RepositoryImages\\VSTSWebTestRepository1647540c.rximgres")
        {
            _applicationundertest = new VSTSWebTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1647540c-5d85-425e-95aa-9f98db6c861e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cddba3de-9db7-4f8b-a553-8247845bac6c")]
        public virtual VSTSWebTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class VSTSWebTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cddba3de-9db7-4f8b-a553-8247845bac6c")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _ranorexlogoInfo;
            RepoItemInfo _freetrialInfo;
            RepoItemInfo _experiencethepowerofranorexstudiohInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, true, "cddba3de-9db7-4f8b-a553-8247845bac6c", "")
            {
                _ranorexlogoInfo = new RepoItemInfo(this, "RanorexLogo", "body/header/div/div[1]/nav/div/div[1]//a[@href='https://www.ranorex.com/']/img[@alt='Ranorex Logo']", 30000, null, "60b9ce67-6db9-4255-b7ba-933af9a2106f");
                _freetrialInfo = new RepoItemInfo(this, "FREETRIAL", "body/header/div/div[1]/nav/div/div[1]//ul/a[@innertext='FREE TRIAL']", 30000, null, "52cea2d8-9ed4-4a52-97c8-ea31db8a84e1");
                _experiencethepowerofranorexstudiohInfo = new RepoItemInfo(this, "ExperienceThePowerOfRanorexStudioH", "body/div[1]/div//div[@id='et_builder_outer_content']/div/div/div/div[1]/div[1]//div[@innertext~'^Get\\ started\\ with\\ your\\ free,\\ full-featured\\ 30-day\\ ']/h1[@innertext='Experience the power of Ranorex Studio hands-on']", 30000, null, "5b550cd2-4da0-4a62-8983-c039544e2a0e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cddba3de-9db7-4f8b-a553-8247845bac6c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cddba3de-9db7-4f8b-a553-8247845bac6c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RanorexLogo item.
            /// </summary>
            [RepositoryItem("60b9ce67-6db9-4255-b7ba-933af9a2106f")]
            public virtual Ranorex.ImgTag RanorexLogo
            {
                get
                {
                    return _ranorexlogoInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The RanorexLogo item info.
            /// </summary>
            [RepositoryItemInfo("60b9ce67-6db9-4255-b7ba-933af9a2106f")]
            public virtual RepoItemInfo RanorexLogoInfo
            {
                get
                {
                    return _ranorexlogoInfo;
                }
            }

            /// <summary>
            /// The FREETRIAL item.
            /// </summary>
            [RepositoryItem("52cea2d8-9ed4-4a52-97c8-ea31db8a84e1")]
            public virtual Ranorex.ATag FREETRIAL
            {
                get
                {
                    return _freetrialInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The FREETRIAL item info.
            /// </summary>
            [RepositoryItemInfo("52cea2d8-9ed4-4a52-97c8-ea31db8a84e1")]
            public virtual RepoItemInfo FREETRIALInfo
            {
                get
                {
                    return _freetrialInfo;
                }
            }

            /// <summary>
            /// The ExperienceThePowerOfRanorexStudioH item.
            /// </summary>
            [RepositoryItem("5b550cd2-4da0-4a62-8983-c039544e2a0e")]
            public virtual Ranorex.H1Tag ExperienceThePowerOfRanorexStudioH
            {
                get
                {
                    return _experiencethepowerofranorexstudiohInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The ExperienceThePowerOfRanorexStudioH item info.
            /// </summary>
            [RepositoryItemInfo("5b550cd2-4da0-4a62-8983-c039544e2a0e")]
            public virtual RepoItemInfo ExperienceThePowerOfRanorexStudioHInfo
            {
                get
                {
                    return _experiencethepowerofranorexstudiohInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}